use cs121DB;
DROP TABLE IF EXISTS Visited_URL, WordFreq, Timing;
	
CREATE TABLE IF NOT EXISTS Visited_URL(
	Id INT PRIMARY KEY AUTO_INCREMENT, 
    Url VARCHAR(767) UNIQUE,
	SubDomain VARCHAR(767),
	NumberOfWords INT NOT NULL DEFAULT 0,
	WebText LONGTEXT, 
	Html LONGTEXT
	);

CREATE TABLE IF NOT EXISTS WordFreq(
	Word VARCHAR(767) PRIMARY KEY, 
    Freq INT NOT NULL DEFAULT 0
	);

CREATE TABLE IF NOT EXISTS Timing(
	RunNumber INT PRIMARY KEY AUTO_INCREMENT,
	RunTime INT
	);


